services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    hostname: rwDietPi
    ports:
      - "53:53/tcp" # DNS over TCP
      - "53:53/udp" # DNS over UDP
    env_file:
      - ../secrets/.env
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: $SECURE_PASSWORD
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    networks:
      - core
    healthcheck:
      test:
        ["CMD", "dig", "+short", "+tries=1", "+time=1", "@127.0.0.1", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 3

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - ./secrets/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - core
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  pihole_config:
    name: pihole_config
  pihole_dnsmasq:
    name: pihole_dnsmasq
  portainer_data:
    name: portainer_data

networks:
  core:
    external: true
